#From k8s.gcr.io/kube-apiserver-amd64:v1.8.15
From k8s.gcr.io/kube-apiserver-amd64:lastest
From k8s.gcr.io/kube-scheduler-amd64:lastest
From k8s.gcr.io/kube-controller-manager-amd64:lastest
From k8s.gcr.io/kube-proxy-amd64:lastest
From k8s.gcr.io/k8s-dns-kube-dns-amd64:lastest
From k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:lastest
From k8s.gcr.io/k8s-dns-sidecar-amd64:lastest
From k8s.gcr.io/etcd-amd64:lastest
From k8s.gcr.io/flannel:v0.10.0-amd64
From k8s.gcr.io/pause-amd64:lastest
From k8s.gcr.io/kube-proxy-amd64:lastest
From k8s.gcr.io/flannel:v0.10.0-amd64
From k8s.gcr.io/pause-amd64:lastest
From k8s.gcr.io/kubernetes-dashboard-amd64:lastest
From k8s.gcr.io/heapster-influxdb-amd64:lastest
From k8s.gcr.io/heapster-grafana-amd64:lastest
From k8s.gcr.io/heapster-amd64:lastest
